### ISSUE TITLE
Cannot get BLT-CSE to work with HoxHud

### ISSUE THREAD

**Issue by Oirad16** [HoxHud/BLT-CSE-bin#1]
I can only get either one or the other to work depending on if I have the HoxHud.dll or the IPHLPAPI.dll/PD2BLTCSE.dll in the lib/Native folder. The game does not launch if more than one .dll is in that folder, but a Payday process does launch in the background.
![ss 2015-05-12 at 09 18 30](https://cloud.githubusercontent.com/assets/12420828/7602158/b5c7a726-f8ee-11e4-9690-8e1842a27d8e.png)
![ss 2015-05-12 at 09 17 57](https://cloud.githubusercontent.com/assets/12420828/7602159/b5c82d90-f8ee-11e4-9361-dc16acb602b4.png)

This is what my Payday folders look like, and the game does not start unless I remove one of the dlls from the Native folder.

**Comment by Olipro** [comment]
rename lib/Native/IPHLPAPI.dll to BLTCSE.dll and let me know if that fixes it.

**Comment by Oirad16** [comment]
It did. Thanks.
